# Generated by Django 2.0.2 on 2018-03-10 17:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='profile_user',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='reported_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('TO_DO', 'TO_DO'), ('DOING', 'DOING'), ('DONE', 'DONE')], default='TO_DO', max_length=10),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
